spring.application.name=wms
spring.datasource.url=jdbc:postgresql://localhost:5432/wms-db
spring.datasource.username=wms-owner
spring.datasource.password=password
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

spring.jpa.properties.hibernate.dialect=PostgreSQL
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
