create table warehouses
(
    id      bigint generated by default as identity
        constraint id
            primary key,
    name    varchar,
    address varchar
);

create table category
(
    category_id   bigint generated by default as identity
        constraint category_pk
            primary key,
    category_name varchar not null
);

create table products
(
    product_id   bigint generated by default as identity
        constraint products_pk
            primary key,
    product_name varchar not null,
    product_sku  varchar not null
        constraint uq_products_sku
            unique,
    unit         varchar,
    category_id  bigint
        constraint products_category_category_id_fk
            references category
            on delete restrict
);

create index idx_products_category_id
    on products (category_id);

create table locations
(
    location_id  bigint generated by default as identity
        constraint locations_pk
            primary key,
    warehouse_id bigint  not null
        constraint locations_warehouses_id_fk
            references warehouses,
    zone         varchar not null,
    aisle        varchar not null,
    rack         varchar,
    shelf        varchar not null,
    bin          varchar not null,
    capacity     integer,
    code         varchar not null
        constraint uq_locations_code
            unique
);

create index idx_locations_warehouse_id
    on locations (warehouse_id);

create table supplier
(
    supplier_id   bigint generated always as identity
        constraint supplier_pk
            primary key,
    supplier_name varchar not null
);

create table batches
(
    batch_id    bigint generated always as identity
        constraint batches_pk
            primary key,
    product_id  bigint not null
        constraint batches_products_product_id_fk
            references products
            on update cascade on delete cascade,
    lot_number  varchar,
    expiry_date date,
    supplier_id bigint
        constraint batches_supplier_supplier_id_fk
            references supplier
            on delete set null
);

create table stock
(
    stock_id          bigint generated by default as identity
        constraint stock_pk
            primary key,
    location_id       bigint            not null
        constraint stock_locations_location_id_fk
            references locations
            on update cascade on delete cascade,
    product_id        bigint            not null
        constraint stock_products_product_id_fk
            references products
            on delete restrict,
    quantity          integer           not null
        constraint chk_stock_quantity
            check (quantity >= 0),
    reserved_quantity integer default 0 not null
        constraint chk_stock_reserved
            check (reserved_quantity >= 0),
    batch_id          bigint            not null
        references batches,
    constraint uq_stock_product_location_batch
        unique (product_id, location_id, batch_id)
);

create index idx_stock_location_id
    on stock (location_id);

create index idx_stock_product_id
    on stock (product_id);

create index idx_batches_product_id
    on batches (product_id);

create index idx_batches_supplier_id
    on batches (supplier_id);

create table customers
(
    customer_id   bigint generated always as identity
        constraint customers_pk
            primary key,
    customer_name varchar not null
);

create table outbound_orders
(
    order_id     bigint generated always as identity
        constraint outbound_orders_pk
            primary key,
    warehouse_id bigint    not null
        constraint outbound_orders_warehouses_id_fk
            references warehouses,
    status       varchar   not null
        constraint chk_outbound_status
            check ((status)::text = ANY
        ((ARRAY ['NEW'::character varying, 'PROCESSING'::character varying, 'SHIPPED'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])),
    created_at   timestamp not null,
    customer_id  bigint    not null
        constraint outbound_orders_customers_customer_id_fk
            references customers
);

create table outbound_items
(
    product_id bigint  not null
        constraint outbound_items_products_product_id_fk
            references products,
    order_id   bigint  not null
        constraint outbound_items_outbound_orders_order_id_fk
            references outbound_orders
            on delete cascade,
    quantity   integer not null,
    id         bigint  not null
        constraint outbound_items_pk
            primary key
);

create index idx_outbound_items_order_id
    on outbound_items (order_id);

create index idx_outbound_items_product_id
    on outbound_items (product_id);

create index idx_outbound_orders_customer_id
    on outbound_orders (customer_id);

create index idx_outbound_orders_warehouse_id
    on outbound_orders (warehouse_id);

create table inbound_orders
(
    order_id     bigint generated always as identity
        constraint inbound_orders_pk
            primary key,
    warehouse_id bigint    not null
        constraint inbound_orders_warehouses_id_fk
            references warehouses,
    supplier_id  bigint    not null
        constraint inbound_orders_supplier_supplier_id_fk
            references supplier,
    status       varchar   not null,
    created_at   timestamp not null
);

create index idx_inbound_orders_supplier_id
    on inbound_orders (supplier_id);

create index idx_inbound_orders_warehouse_id
    on inbound_orders (warehouse_id);

create table inbound_items
(
    id         bigint generated always as identity
        constraint inbound_items_pk
            primary key,
    product_id bigint  not null
        constraint inbound_items_products_product_id_fk
            references products,
    order_id   bigint  not null
        constraint inbound_items_inbound_orders_order_id_fk
            references inbound_orders,
    quantity   integer not null
);

create index idx_inbound_items_order_id
    on inbound_items (order_id);

create index idx_inbound_items_product_id
    on inbound_items (product_id);

create table users
(
    id            bigint generated always as identity
        constraint users_pk
            primary key,
    username      varchar   not null
        constraint uq_users_username
            unique,
    password_hash varchar,
    email         varchar
        constraint uq_users_email
            unique,
    role          varchar   not null,
    created_at    timestamp not null
);

create table stock_movements
(
    id               bigint generated always as identity
        constraint stock_movements_pk
            primary key,
    from_location_id bigint
        constraint stock_movements_locations_location_id_fk
            references locations,
    to_location_id   bigint
        constraint stock_movements_locations_location_id_fk_2
            references locations,
    user_id          bigint                  not null
        constraint stock_movements_users_id_fk
            references users,
    movement_type    varchar                 not null,
    quantity         integer                 not null
        constraint chk_movement_quantity
            check (quantity > 0),
    product_id       bigint                  not null
        constraint stock_movements_products_product_id_fk
            references products,
    created_at       timestamp default now() not null
);

create index idx_stock_movements_product_id
    on stock_movements (product_id);

create index idx_stock_movements_from_location_id
    on stock_movements (from_location_id);

create index idx_stock_movements_to_location_id
    on stock_movements (to_location_id);

create index idx_stock_movements_user_id
    on stock_movements (user_id);

